/**
 * Shape guards for the vendored data modules. These are generated by
 * `scripts/generate-data.mjs`; CI additionally re-runs the generator and
 * diffs the result (`yarn verify:data`) so a language-common bump cannot
 * silently change what ships.
 */
import { ADJACENCY_GRAPHS } from '../data/adjacencyGraphs.generated';
import { EN_COMMON_LITE } from '../data/enCommonLite.generated';

describe('generated data', () => {
  describe('EN_COMMON_LITE', () => {
    it('holds exactly the documented cutoff', () => {
      expect(EN_COMMON_LITE).toHaveLength(4000);
    });

    it('contains no duplicates', () => {
      expect(new Set(EN_COMMON_LITE).size).toBe(EN_COMMON_LITE.length);
    });

    it('is entirely non-empty strings', () => {
      for (const entry of EN_COMMON_LITE) {
        expect(typeof entry).toBe('string');
        expect(entry.length).toBeGreaterThan(0);
      }
    });

    it('preserves frequency order', () => {
      // Rank order IS the scoring signal, so an accidental sort would be a
      // silent correctness regression rather than a cosmetic diff.
      expect(EN_COMMON_LITE[0]).toBe('123456');
      expect(EN_COMMON_LITE.indexOf('password')).toBeLessThan(20);
      expect([...EN_COMMON_LITE]).not.toEqual([...EN_COMMON_LITE].sort());
    });
  });

  describe('ADJACENCY_GRAPHS', () => {
    it('ships every keyboard layout', () => {
      expect(Object.keys(ADJACENCY_GRAPHS).sort()).toEqual([
        'azerty',
        'dvorak',
        'keypad',
        'keypadMac',
        'qwerty',
        'qwertz',
      ]);
    });

    it('maps each key to an array of neighbours', () => {
      const qwerty = ADJACENCY_GRAPHS['qwerty'];
      expect(qwerty).toBeDefined();
      expect(Array.isArray(qwerty?.['q'])).toBe(true);
    });
  });
});
